In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
Trip2019 = pd.read_csv("Trips_2019_Q1.csv")
Trip2020 = pd.read_csv("Trips_2020_Q1.csv")

/tmp/ipykernel_1497/3896081321.py:1: DtypeWarning: Columns (17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  Trip2019 = pd.read_csv("Trips_2019_Q1.csv")
/tmp/ipykernel_1497/3896081321.py:2: DtypeWarning: Columns (18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  Trip2020 = pd.read_csv("Trips_2020_Q1.csv")

In [ ]:
Trip2019.head(5)

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear,ride_lengt,Valid/Not,day_of_week,day_name,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,21742443,1/1/2019 0:04:37,1/1/2019 0:11:07,2167,390,199,Wabash Ave & Grand Ave,84,Milwaukee Ave & Grand Ave,Subscriber,Male,1989.0,0:06:30,VALID,3,Tuesday,NaN,NaN,NaN,NaN
1,21742444,1/1/2019 0:08:13,1/1/2019 0:15:34,4386,441,44,State St & Randolph St,624,Dearborn St & Van Buren St (*),Subscriber,Female,1990.0,0:07:21,VALID,3,Tuesday,NaN,NaN,NaN,NaN
2,21742445,1/1/2019 0:13:23,1/1/2019 0:27:12,1524,829,15,Racine Ave & 18th St,644,Western Ave & Fillmore St (*),Subscriber,Female,1994.0,0:13:49,VALID,3,Tuesday,NaN,NaN,Ride_Length,Day_of_week
3,21742446,1/1/2019 0:13:45,1/1/2019 0:43:28,252,"1,783.00",123,California Ave & Milwaukee Ave,176,Clark St & Elm St,Subscriber,Male,1993.0,0:29:43,VALID,3,Tuesday,NaN,Mean,0:16:56,NaN
4,21742447,1/1/2019 0:14:52,1/1/2019 0:20:56,1170,364,173,Mies van der Rohe Way & Chicago Ave,35,Streeter Dr & Grand Ave,Subscriber,Male,1994.0,0:06:04,VALID,3,Tuesday,NaN,Max,1:20:22,NaN

In [ ]:
Trip2020.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_lng,member_casual,ride_length,Valid/Not,day_of_week,day_name,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,6FABADDD595AF922,docked_bike,27/03/20 15:15:26,27/03/20 15:06:14,HQ QR,675,HQ QR,675.0,41.8899,-87.6803,...,-87.6803,casual,-0:09:12,INVALID - DURATION,6,Friday,NaN,NaN,NaN,NaN
1,13BCB74BAFDADB21,docked_bike,27/03/20 14:59:51,27/03/20 14:58:18,HQ QR,675,HQ QR,675.0,41.8899,-87.6803,...,-87.6803,casual,-0:01:33,INVALID - DURATION,6,Friday,NaN,NaN,NaN,NaN
2,867C195C5650C884,docked_bike,27/03/20 15:00:57,27/03/20 14:59:38,HQ QR,675,HQ QR,675.0,41.8899,-87.6803,...,-87.6803,casual,-0:01:19,INVALID - DURATION,6,Friday,NaN,NaN,Ride_Length,Day_of_week
3,3361A4413B4813B8,docked_bike,20/03/20 10:18:41,20/03/20 10:18:18,HQ QR,675,HQ QR,675.0,41.8899,-87.6803,...,-87.6803,casual,-0:00:23,INVALID - DURATION,6,Friday,NaN,Mean,NaN,NaN
4,B0565BEDAF8D721F,docked_bike,18/03/20 11:30:34,18/03/20 11:30:12,HQ QR,675,HQ QR,675.0,41.8899,-87.6803,...,-87.6803,casual,-0:00:22,INVALID - DURATION,4,Wednesday,NaN,Max,NaN,NaN

In [ ]:
"""
Mengambil kolom yang diperlukan dari dataframe Trip2019 dan Trip2020
"""

columns_needed19 = ["trip_id", "start_time","end_time","from_station_name","to_station_name","usertype","ride_lengt","day_of_week","day_name"]
df2019 = Trip2019[columns_needed19].copy()

columns_needed20 = ["ride_id","started_at","ended_at","start_station_name","end_station_name","member_casual","ride_length","day_of_week","day_name"]
df2020 = Trip2020[columns_needed20].copy()

In [ ]:
df2019.head(5)

,trip_id,start_time,end_time,from_station_name,to_station_name,usertype,ride_lengt,day_of_week,day_name
0,21742443,1/1/2019 0:04:37,1/1/2019 0:11:07,Wabash Ave & Grand Ave,Milwaukee Ave & Grand Ave,Subscriber,0:06:30,3,Tuesday
1,21742444,1/1/2019 0:08:13,1/1/2019 0:15:34,State St & Randolph St,Dearborn St & Van Buren St (*),Subscriber,0:07:21,3,Tuesday
2,21742445,1/1/2019 0:13:23,1/1/2019 0:27:12,Racine Ave & 18th St,Western Ave & Fillmore St (*),Subscriber,0:13:49,3,Tuesday
3,21742446,1/1/2019 0:13:45,1/1/2019 0:43:28,California Ave & Milwaukee Ave,Clark St & Elm St,Subscriber,0:29:43,3,Tuesday
4,21742447,1/1/2019 0:14:52,1/1/2019 0:20:56,Mies van der Rohe Way & Chicago Ave,Streeter Dr & Grand Ave,Subscriber,0:06:04,3,Tuesday

In [ ]:
df2020.head(5)

,ride_id,started_at,ended_at,start_station_name,end_station_name,member_casual,ride_length,day_of_week,day_name
0,6FABADDD595AF922,27/03/20 15:15:26,27/03/20 15:06:14,HQ QR,HQ QR,casual,-0:09:12,6,Friday
1,13BCB74BAFDADB21,27/03/20 14:59:51,27/03/20 14:58:18,HQ QR,HQ QR,casual,-0:01:33,6,Friday
2,867C195C5650C884,27/03/20 15:00:57,27/03/20 14:59:38,HQ QR,HQ QR,casual,-0:01:19,6,Friday
3,3361A4413B4813B8,20/03/20 10:18:41,20/03/20 10:18:18,HQ QR,HQ QR,casual,-0:00:23,6,Friday
4,B0565BEDAF8D721F,18/03/20 11:30:34,18/03/20 11:30:12,HQ QR,HQ QR,casual,-0:00:22,4,Wednesday

In [ ]:
"""
Mengecek apakah ada missing value pada dataframe
"""
df2019.isnull().sum()

trip_id              0
start_time           0
end_time             0
from_station_name    0
to_station_name      0
usertype             0
ride_lengt           0
day_of_week          0
day_name             0
dtype: int64

In [ ]:
"""
Mengecek apakah ada missing value pada dataframe
"""
df2020.isnull().sum()

ride_id               0
started_at            0
ended_at              0
start_station_name    0
end_station_name      1
member_casual         0
ride_length           0
day_of_week           0
day_name              0
dtype: int64

In [ ]:
"""
Menghapus missing value pada dataframe
"""
df2019.dropna(inplace = True)
df2020.dropna(inplace = True)

In [ ]:
"""
Mengecek apakah ada missing value pada dataframe setelah dihapus
"""
df2019.isnull().sum()

trip_id              0
start_time           0
end_time             0
from_station_name    0
to_station_name      0
usertype             0
ride_lengt           0
day_of_week          0
day_name             0
dtype: int64

In [ ]:
"""
Mengecek apakah ada missing value pada dataframe setelah dihapus
"""
df2020.isnull().sum()

ride_id               0
started_at            0
ended_at              0
start_station_name    0
end_station_name      0
member_casual         0
ride_length           0
day_of_week           0
day_name              0
dtype: int64

In [ ]:
"""
Mengubah nama kolom pada dataframe Trip2019
"""
rename_2019 = {
    "trip_id": "ride_id",
    "start_time": "started_at",
    "end_time": "ended_at",
    "from_station_name": "start_station_name",
    "to_station_name": "end_station_name",
    "usertype": "member_casual"}

df2019 = df2019.rename(columns=rename_2019)

In [ ]:
"""
Mengecek apakah column 2019 sudah sesuai dengan 2020
"""
print(df2019.columns.tolist())
print(df2020.columns.tolist())

['ride_id', 'started_at', 'ended_at', 'start_station_name', 'end_station_name', 'member_casual', 'ride_lengt', 'day_of_week', 'day_name']
['ride_id', 'started_at', 'ended_at', 'start_station_name', 'end_station_name', 'member_casual', 'ride_length', 'day_of_week', 'day_name']

In [ ]:
"""
Mengubah nama kolom pada dataframe Trip2019
"""
df2019 = df2019.rename(columns={"ride_lengt" : 'ride_length'})

In [ ]:
"""
Mengecek apakah column 2019 sudah sesuai dengan 2020
"""
print(df2019.columns.tolist())
print(df2020.columns.tolist())

['ride_id', 'started_at', 'ended_at', 'start_station_name', 'end_station_name', 'member_casual', 'ride_length', 'day_of_week', 'day_name']
['ride_id', 'started_at', 'ended_at', 'start_station_name', 'end_station_name', 'member_casual', 'ride_length', 'day_of_week', 'day_name']

In [ ]:
"""
Melakukan penggabungan data menjadi 1 dataframe
"""
df = pd.concat([df2019, df2020], ignore_index=True)

In [ ]:
"""
Mengecek apakah jumlah baris pada dataframe sudah sesuai
"""
len(df) == len(df2019) + len(df2020)

True

In [ ]:
"""
Mengubah nama value pada kolom member_casual menjadi member dan casual
"""

df['member_casual'] = df['member_casual'].replace({'Customer':'casual','Subscriber':'member'})


"""
Mengubah tipe data pada kolom started_at dan ended_at menjadi datetime
"""

for column in ['started_at','ended_at'] :
  df[column] = pd.to_datetime(
      df[column],
      format = 'mixed',
      dayfirst = True,
      errors = 'coerce'
  )

In [ ]:
"""
Mengecek apakah data type sudah sesuai
"""
df[['started_at','ended_at']].dtypes

started_at    datetime64[ns]
ended_at      datetime64[ns]
dtype: object

In [162]:
"""
Menambahkan beberapa column untuk memudahkan analisis data
"""

df['ride_length'] = pd.to_timedelta(df['ride_length'])
df['ride_length_second'] = df['ride_length'].dt.total_seconds()
df['ride_length_minute'] = round(df['ride_length_second']/60,1)

df['year'] = df['started_at'].dt.year
df['month'] = df['started_at'].dt.month
df['month_name'] = df['started_at'].dt.month_name()
df["start_hour"] = df["started_at"].dt.hour

In [163]:
df.head(10)

,ride_id,started_at,ended_at,start_station_name,end_station_name,member_casual,ride_length,day_of_week,day_name,ride_length_second,ride_length_minute,year,month,month_name,start_hour
0,21742443,2019-01-01 00:04:37,2019-01-01 00:11:07,Wabash Ave & Grand Ave,Milwaukee Ave & Grand Ave,member,0 days 00:06:30,3,Tuesday,390.0,6.5,2019,1,January,0
1,21742444,2019-01-01 00:08:13,2019-01-01 00:15:34,State St & Randolph St,Dearborn St & Van Buren St (*),member,0 days 00:07:21,3,Tuesday,441.0,7.4,2019,1,January,0
2,21742445,2019-01-01 00:13:23,2019-01-01 00:27:12,Racine Ave & 18th St,Western Ave & Fillmore St (*),member,0 days 00:13:49,3,Tuesday,829.0,13.8,2019,1,January,0
3,21742446,2019-01-01 00:13:45,2019-01-01 00:43:28,California Ave & Milwaukee Ave,Clark St & Elm St,member,0 days 00:29:43,3,Tuesday,1783.0,29.7,2019,1,January,0
4,21742447,2019-01-01 00:14:52,2019-01-01 00:20:56,Mies van der Rohe Way & Chicago Ave,Streeter Dr & Grand Ave,member,0 days 00:06:04,3,Tuesday,364.0,6.1,2019,1,January,0
5,21742448,2019-01-01 00:15:33,2019-01-01 00:19:09,LaSalle St & Washington St,Dearborn St & Monroe St,member,0 days 00:03:36,3,Tuesday,216.0,3.6,2019,1,January,0
6,21742449,2019-01-01 00:16:06,2019-01-01 00:19:03,LaSalle St & Washington St,Dearborn St & Monroe St,member,0 days 00:02:57,3,Tuesday,177.0,3.0,2019,1,January,0
7,21742450,2019-01-01 00:18:41,2019-01-01 00:20:21,St. Clair St & Erie St,McClurg Ct & Erie St,member,0 days 00:01:40,3,Tuesday,100.0,1.7,2019,1,January,0
8,21742451,2019-01-01 00:18:43,2019-01-01 00:47:30,Fort Dearborn Dr & 31st St,State St & 33rd St,member,0 days 00:28:47,3,Tuesday,1727.0,28.8,2019,1,January,0
9,21742452,2019-01-01 00:19:18,2019-01-01 00:24:54,Lake Shore Dr & North Blvd,Clark St & Lincoln Ave,member,0 days 00:05:36,3,Tuesday,336.0,5.6,2019,1,January,0

In [164]:
file_name = "Trip_Q1_2019_vs_Trip_Q1_2020.csv"

df.to_csv(file_name, index=False)

print(f"Berhasil export: {file_name}")

Berhasil export: Trip_Q1_2019_vs_Trip_Q1_2020.csv

In [165]:
from google.colab import files

files.download(file_name)